source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.2'

use_frameworks!
target 'WebSocketApiObjC_Tests' do
  pod 'WebSocketApiObjC', :path => '../'
  
  pod 'Specta'
  pod 'Expecta'
  pod 'SocketRocket', '~> 0.5.1'
  pod 'OHHTTPStubs', '~> 5.2.3'
end
