language: objective-c
osx_image: xcode8.2
xcode_workspace: Example/WebSocketApiObjC.xcworkspace
xcode_scheme: WebSocketApiObjC-Example
podfile: Example/Podfile
script:
 - xctool -workspace Example/WebSocketApiObjC.xcworkspace -scheme WebSocketApiObjC-Example -destination name="iPhone 6s" build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
before_install: 
 - pod update --project-directory=Example/
