language: objective-c
osx_image: xcode8.2
xcode_workspace: Example/WebSocketApiObjC.xcworkspace
xcode_scheme: WebSocketApiObjC-Example
podfile: Example/Podfile
script:
 - xcodebuild test -workspace Example/WebSocketApiObjC.xcworkspace -scheme WebSocketApiObjC-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
before_install: 
 - pod update --project-directory=Example/
